### ISSUE TITLE
Unable to build.

### ISSUE THREAD

**Issue by AlienAlloy2** [ArthurCose/Minicraft-DS-Edition#2]
Either im very dense or you cant build. I know in the pc version you can place floors and walls but here i cant even craft planks and walls. This is a major dealbreaker for me since i end up roaming the world and eventually dying cause i cant settle anywhere or store my items. This is a pretty light game, and the source codes available, so i think it would be easy to port the entire game to ds.

**Comment by Nohviact** [comment]
Original Minicraft never allowed you to build walls like that. You literally had to dig holes to keep zombies and slimes away from your area. It's silly, I know

**Comment by AlienAlloy2** [comment]
> Original Minicraft never allowed you to build walls like that. You literally had to dig holes to keep zombies and slimes away from your area. It's silly, I know

I have played it on pc and there is building blocks and you can build. It might be because its Minicraft+. Is it possible that such a no brainer mechanic is not in the base game?

**Comment by ArthurCose** [comment]
The original Minicraft was built in 48 hours as part of a game jam. Notch couldn't add too much due to time constraints and it seems he focused more on making a challenging and completable game.

Minicraft+ isn't a good reference for what was in the original game since it's been in active development and has been adding new features for over a decade. 

The source for this project is a somewhat close port / translation of an archived copy of the original source code.
